<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RALPH_LOAD_MANAGEMENT</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LoadManagementBusinessLogic\**" />
    <Compile Remove="LoadManagementDataLayer\**" />
    <Compile Remove="LoadManagementModelLayer\**" />
    <EmbeddedResource Remove="LoadManagementBusinessLogic\**" />
    <EmbeddedResource Remove="LoadManagementDataLayer\**" />
    <EmbeddedResource Remove="LoadManagementModelLayer\**" />
    <None Remove="LoadManagementBusinessLogic\**" />
    <None Remove="LoadManagementDataLayer\**" />
    <None Remove="LoadManagementModelLayer\**" />
  </ItemGroup>

</Project>
